openapi: 3.0.1
info:
  title: UNECE Recommendation 20 - Codes for Units of Measure Used in International Trade
  description: |
    Recommendation 20 Provides three character alphabetic and alphanumeric codes for representing units of measurement for length, area, volume/capacity, mass (weight), time, and other quantities used in international trade. The codes are intended for use in manual and/or automated systems for the exchange of information between participants in international trade.Facilitates use of Recommendation 20. The code list is presented in three separate annexes.

    Annex I – Code elements listed by quantity category;

    Annex II – Code elements listed by unit of measure name;

    Annex III – Code elements listed by common code;
  contact:
    name: UNECE Recommendations
    url: https://www.unece.org/tradewelcome/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/cefactrecommendationsrec-index/code-list-recommendations.html
  version: "3.0.1-oas3"
servers:
- url: "https://codelists.api.edi3.org/recommendation-20"
paths:
  /quantityCategory:
    get:
      tags:
      - quantityCategory
      summary: Search for units of measure as defined in rec 20
      description: This api will return a (paged) list of units of measure codes
      operationId: searchQuantityCategory
      parameters:
      - name: GroupNumber
        in: query
        description: ""
        schema:
          type: string
      - name: Sector
        in: query
        description: ""
        schema:
          type: string
      - name: GroupID
        in: query
        description: ""
        schema:
          type: string
      - name: Quantity
        in: query
        description: "The name of the physical phenomenon being measured"
        schema:
          type: string
      - name: Level/Category
        in: query
        description: "Identification of the normative or informative relevance of the unit"
        schema:
          type: string
      - name: Status
        in: query
        description: "An indication of the maintenance status of individual units of measure"
        schema:
          type: string
      - name: CommonCode
        in: query
        description: "This is the recommended single list of standard codes"
        schema:
          type: string
      - name: Name
        in: query
        description: "The name of the unit of measure"
        schema:
          type: string
      - name: Description
        in: query
        description: "A plain text specification of the named unit of measure"
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuantityCategories'
              example:
              - GroupNumber: 01
                Sector: Space and Time
                GroupID: 17
                Quantity: solid angle
                Level/Category: 1S
                Status: ""
                CommonCode: M55
                Name: metre per radiant
                Description: Unit of the translation factor for implementation from rotation to linear movement.
        400:
          description: ' Bad request - Issue with parameter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                identifier: a710a2af-4f0d-458b-8792-23fe4f736d9d
                error: pagesize needs to be between 1 and 1000.
        404:
          description: No data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                identifier: b1f1fef1-59ad-4978-bed8-3ff96d6d3587
                error: No quantity measure found
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                identifier: 0407936e-d2ad-41e9-99e2-05a5919c3075
                error: An unexpected exception occured
  /unitOfMeasure:
    get:
      tags:
      - unitOfMeasure
      summary: Search for units of measure as defined in rec 20
      description: This api will return a (paged) list of units of measure codes
      operationId: searchUnitOfMeasure
      parameters:
      - name: CommonCode
        in: query
        description: "This is the recommended single list of standard codes"
        schema:
          type: string
      - name: Name
        in: query
        description: "The name of the unit of measure"
        schema:
          type: string
      - name: Description
        in: query
        description: "A plain text specification of the named unit of measure"
        schema:
          type: string
      - name: Level/Category
        in: query
        description: "Identification of the normative or informative relevance of the unit"
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnitsOfMeasure'
              example:
              - CommonCode: 10
                Name: group
                Description: A unit of count defining the number of groups (group; set of items classified together).
                Level/Category: 3.9
        400:
          description: ' Bad request - Issue with parameter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                identifier: a710a2af-4f0d-458b-8792-23fe4f736d9d
                error: pagesize needs to be between 1 and 1000.
        404:
          description: No data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                identifier: b1f1fef1-59ad-4978-bed8-3ff96d6d3587
                error: No units of measure found
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                identifier: 0407936e-d2ad-41e9-99e2-05a5919c3075
                error: An unexpected exception occured
components:
  schemas:
    Error:
      type: object
      properties:
        identifier:
          type: string
        error:
          type: string
    QuantityCategories:
      type: array
      items:
        $ref: '#/components/schemas/QuantityCategory'
    QuantityCategory:
      type: object
      properties:
        GroupNumber:
          description: ""
          type: string
        Sector:
          description: ""
          type: string
        GroupID:
          description: ""
          type: string
        Quantity:
          description: "The name of the physical phenomenon being measured"
          type: string
        Level/Category:
          description: "Identification of the normative or informative relevance of the unit"
          type: string
        Status:
          description: "An indication of the maintenance status of individual units of measure"
          type: string
        CommonCode:
          description: "This is the recommended single list of standard codes"
          type: string
        Name:
          description: "The name of the unit of measure"
          type: string
        Description:
          description: "A plain text specification of the named unit of measure"
          type: string
    UnitsOfMeasure:
      type: array
      items:
        $ref: '#/components/schemas/UnitOfMeasure'
    UnitOfMeasure:
      type: object
      properties:
        CommonCode:
          description: "This is the recommended single list of standard codes"
          type: string
        Name:
          description: "The name of the unit of measure"
          type: string
        Description:
          description: "A plain text specification of the named unit of measure"
          type: string
        Level/Category:
          description: "Identification of the normative or informative relevance of the unit"
          type: string
      